- hosts: tag_Name_ansible_wn
  become: true
  tasks:
    - name: copy war file from jenkins to tomcat
      copy:
        src: webapp/target/webapp.war #add war file
        dest: /opt/tomcat/webapps/
#add testing comit
